In [ ]:
import sys
sys.path.append('/Users/IvanTang/hep/E320simulator')

In [21]:
import polars as pl
from src.geometry import SENSOR_TO_LAYER
data_path = '/Users/IvanTang/hep/data_Run502/simulation/sim_clusters_train.parquet'
clusters_df = (
    pl.read_parquet(data_path)
    #.filter(pl.col("det_type") == "pixel")
    #.with_columns(
        #pl.col("sensor_id").replace(SENSOR_TO_LAYER).cast(pl.Int8).alias("layer_id"),
    #)
)
df

shape: (2_506_035, 12)
┌─────────┬──────────┬──────────┬────────────┬───┬──────┬──────────┬───────────┬───────────────┐
│ node_id ┆ event_id ┆ layer_id ┆ x_trk_mm   ┆ … ┆ size ┆ track_id ┆ is_signal ┆ particle_type │
│ ---     ┆ ---      ┆ ---      ┆ ---        ┆   ┆ ---  ┆ ---      ┆ ---       ┆ ---           │
│ u32     ┆ i64      ┆ i64      ┆ f64        ┆   ┆ i64  ┆ i64      ┆ bool      ┆ str           │
╞═════════╪══════════╪══════════╪════════════╪═══╪══════╪══════════╪═══════════╪═══════════════╡
│ 0       ┆ 0        ┆ 0        ┆ 10.648924  ┆ … ┆ 3    ┆ -1       ┆ false     ┆ background    │
│ 1       ┆ 0        ┆ 0        ┆ 5.861041   ┆ … ┆ 2    ┆ -1       ┆ false     ┆ background    │
│ 2       ┆ 0        ┆ 0        ┆ -12.051309 ┆ … ┆ 1    ┆ -1       ┆ false     ┆ background    │
│ 3       ┆ 0        ┆ 0        ┆ 14.124081  ┆ … ┆ 1    ┆ -1       ┆ false     ┆ background    │
│ 4       ┆ 0        ┆ 0        ┆ 7.754805   ┆ … ┆ 1    ┆ -1       ┆ false     ┆ background    │
│ …       ┆ …        ┆ …        ┆ …          ┆ … ┆ …    ┆ …        ┆ …         ┆ …             │
│ 2506030 ┆ 9999     ┆ 4        ┆ -0.101063  ┆ … ┆ 4    ┆ -1       ┆ false     ┆ background    │
│ 2506031 ┆ 9999     ┆ 4        ┆ 10.096109  ┆ … ┆ 2    ┆ -1       ┆ false     ┆ background    │
│ 2506032 ┆ 9999     ┆ 4        ┆ 11.866134  ┆ … ┆ 1    ┆ -1       ┆ false     ┆ background    │
│ 2506033 ┆ 9999     ┆ 4        ┆ 2.783137   ┆ … ┆ 3    ┆ -1       ┆ false     ┆ background    │
│ 2506034 ┆ 9999     ┆ 4        ┆ -5.98806   ┆ … ┆ 1    ┆ -1       ┆ false     ┆ background    │
└─────────┴──────────┴──────────┴────────────┴───┴──────┴──────────┴───────────┴───────────────┘

In [24]:
from src.utils import build_labeled_edges_from_sim
edges_df = build_labeled_edges_from_sim(clusters_df)
edges_df

shape: (12_231_075, 27)
┌──────────┬──────────┬──────────┬───────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ event_id ┆ src_node ┆ dst_node ┆ src_layer ┆ … ┆ track_id_i ┆ track_id_j ┆ edge_labe ┆ is_signal │
│ ---      ┆ ---      ┆ ---      ┆ ---       ┆   ┆ ---        ┆ ---        ┆ l         ┆ _edge     │
│ i64      ┆ i64      ┆ i64      ┆ i64       ┆   ┆ i64        ┆ i64        ┆ ---       ┆ ---       │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ i64       ┆ i64       │
╞══════════╪══════════╪══════════╪═══════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 5267     ┆ 1319905  ┆ 1319965  ┆ 0         ┆ … ┆ -1         ┆ -1         ┆ 0         ┆ 0         │
│ 5267     ┆ 1319905  ┆ 1319975  ┆ 0         ┆ … ┆ -1         ┆ -1         ┆ 0         ┆ 0         │
│ 5267     ┆ 1319905  ┆ 1319979  ┆ 0         ┆ … ┆ -1         ┆ -1         ┆ 0         ┆ 0         │
│ 5267     ┆ 1319905  ┆ 1319988  ┆ 0         ┆ … ┆ -1         ┆ -1         ┆ 0         ┆ 0         │
│ 5267     ┆ 1319905  ┆ 1319998  ┆ 0         ┆ … ┆ -1         ┆ -1         ┆ 0         ┆ 0         │
│ …        ┆ …        ┆ …        ┆ …         ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 8637     ┆ 2164639  ┆ 2164654  ┆ 3         ┆ … ┆ -1         ┆ -1         ┆ 0         ┆ 0         │
│ 8637     ┆ 2164639  ┆ 2164676  ┆ 3         ┆ … ┆ -1         ┆ -1         ┆ 0         ┆ 0         │
│ 8637     ┆ 2164639  ┆ 2164678  ┆ 3         ┆ … ┆ -1         ┆ -1         ┆ 0         ┆ 0         │
│ 8637     ┆ 2164639  ┆ 2164682  ┆ 3         ┆ … ┆ -1         ┆ -1         ┆ 0         ┆ 0         │
│ 8637     ┆ 2164639  ┆ 2164685  ┆ 3         ┆ … ┆ -1         ┆ -1         ┆ 0         ┆ 0         │
└──────────┴──────────┴──────────┴───────────┴───┴────────────┴────────────┴───────────┴───────────┘